### ISSUE TITLE
License text for OTP Generators is not fully visible

### ISSUE THREAD

**Issue by BasicXP** [CooperRS/OTPAuth-Localizations#19]
The first couple of lines are hidden behind the menu bar.

**Comment by BasicXP** [comment]
True for "OTPGenerators" and "RMStore" in build 103.

**Comment by CooperRS** [comment]
Should be solved in 2.0 (107)

**Comment by BasicXP** [comment]
PLCrashReporter and OpenSSL have extra empty line at the end, others either don't or are shorter than the screen, so can't see that.

**Comment by BasicXP** [comment]
On a little unrelated note, there is extra space on top and on the bottom of pretty much all screens, is it according to the guidelines? Imo it's a waste of space x>

**Comment by CooperRS** [comment]
OK, removed those extra lines ;)

And I'm using the grouped table view style as I like it more. And the grouped table view always has some extra space on the top and bottom. At least as long as you don't modify it...
