### ISSUE TITLE
Sync all entries

### ISSUE THREAD

**Issue by BasicXP** [CooperRS/OTPAuth-Localizations#21]
What would be a great feature is to have an encrypted copy of all the keys stored in iCloud in order to be restored on other devices. Doing it one by one is a cumbersome task if there are more than a few of entries.

**Comment by CooperRS** [comment]
Not the first time I received that feature request. At the moment a full iCloud Sync has priority, as this solves the problem in a better way. But exporting all accounts should be considered, too.

But no promises, when I'm done ;)

**Comment by BasicXP** [comment]
That's what I meant :stuck_out_tongue:

**Comment by BasicXP** [comment]
Will appear in the upcoming version.
