### ISSUE TITLE
Xcode project not working

### ISSUE THREAD

**Issue by BasicXP** [CooperRS/OTPAuth-Localizations#22]
Is it needed there at all?
<img src="https://cloud.githubusercontent.com/assets/369699/6039937/5a264da4-ac7d-11e4-8210-d9c4f597d245.png" alt="" width="420"/>

**Comment by CooperRS** [comment]
Redownload the repository. It's not included anymore ;)

**Comment by BasicXP** [comment]
Derp, indeed x>
